services:
  app:
    build: .
    container_name: ipag_app
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
      - ./migrations:/var/www/migrations
      - ./db_migrations:/var/www/db_migrations
      - ./worker.php:/var/www/worker.php
      - ./test_worker.php:/var/www/test_worker.php
    ports:
      - "8080:80"
    depends_on:
      - db
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: ipag_worker
    depends_on:
      - db
      - rabbitmq
    environment:
      DB_HOST: db
      DB_NAME: ipag
      DB_USER: ipaguser
      DB_PASS: ipagpass
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    volumes:
      - ./worker.php:/var/www/worker.php
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
      - ./db_migrations:/var/www/db_migrations
      - ./migrations:/var/www/migrations


  db:
    image: mysql:8.0
    container_name: ipag_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ipag
      MYSQL_USER: ipaguser
      MYSQL_PASSWORD: ipagpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ipag_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db_data:
